#!/usr/bin/env bash
./gradlew -q --console=plain installDist 2> >(grep -v "^Picked up JAVA_TOOL_OPTIONS:" >&2)
"./build/install/simple/bin/simple" "$@" 2> >(grep -v "^Picked up JAVA_TOOL_OPTIONS:" >&2)
